### ISSUE TITLE
Your 570esp loader

### ISSUE THREAD

**Issue by Huykiri0155P** [user202729/CasioEmu#7]
How to use your loader in UCF. I execute it by [AC][<][=] and that doesnt work:v

**Comment by Huykiri0155P** [comment]
![20231224_101417889](https://github.com/user202729/CasioEmu/assets/101462827/02daa986-c962-42d5-8eaf-f97a75630105)

**Comment by user202729** [comment]
Not sure, perhaps try to figure out how to run it on the emulator, then you can inspect the memory etc.

What is the loader supposed to do? The thread is long...
